### ISSUE TITLE
AP CSA Week 1: Innovation-Primatives

### ISSUE THREAD

**Issue by Dylanluo05** [Dylanluo05/DylanLuoAPCSA#4]
### Code.org
![image](https://user-images.githubusercontent.com/9831592/187094086-bec9a571-1dfd-4f71-a986-65a2ef640470.png)

### Creating a Jupyter Notebook using Bash:
![image](https://user-images.githubusercontent.com/9831592/187015303-43c975ad-774f-42b6-b12e-44b498920891.png)

[Week 1 - Bash Jupyter Notebook](https://dylanluo05.github.io/DylanLuoAPCSA/jupyter/2022/08/26/My-First-Bash.html)
[Week 1 - Java Primitives Jupyter Notebook](https://dylanluo05.github.io/DylanLuoAPCSA/jupyter/2022/08/27/Java-Primitives.html)
[Fast Pages College Board Topics Page](https://dylanluo05.github.io/DylanLuoAPCSA/2022/08/27/collegeboard-topics.html)
[Fast Pages Website](https://dylanluo05.github.io/DylanLuoAPCSA/)

**Comment by Ritvik-Keerthi** [comment]
TOTAL SCORE: 2.7+/3

Finished a decent amount of hacks throughout Fastpages, and completed all requirements listed on Canvas
