### ISSUE TITLE
AP CSA Week 2: Innovation - Using Objects

### ISSUE THREAD

**Issue by Dylanluo05** [Dylanluo05/DylanLuoAPCSA#5]
## Code.org
[Code.org Blog Post for all lessons up to lesson 15](https://dylanluo05.github.io/DylanLuoAPCSA/markdown/2022/09/05/Codeorg.html)

## Java Projects
[Java Console Menu](https://dylanluo05.github.io/DylanLuoAPCSA/jupyter/2022/08/31/GUI-menu.html)
[Java Using Objects Collegeboard Notes](https://dylanluo05.github.io/DylanLuoAPCSA/2022/08/27/collegeboard-topics.html)

## Fastpages
[Fastpages](https://dylanluo05.github.io/DylanLuoAPCSA/)

## Teamwork and Share Repository
[Issue displaying team planning, organization, and work](https://github.com/evmyclipz/GroupCSA/issues/1)

**Comment by Ritvik-Keerthi** [comment]
2.7+\3

Did really well with code.org, created unique programs within console menu
